# Generated by Django 3.1 on 2020-09-02 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(blank=True, max_length=50)),
                ('rapstart', models.CharField(blank=True, max_length=50)),
                ('rapend', models.CharField(blank=True, max_length=50)),
                ('pdpstart', models.CharField(blank=True, max_length=50)),
                ('pdpend', models.CharField(blank=True, max_length=50)),
                ('resettlestart', models.CharField(blank=True, max_length=50)),
                ('resettleend', models.CharField(blank=True, max_length=50)),
                ('supervisionstart', models.CharField(blank=True, max_length=50)),
                ('supervisionend', models.CharField(blank=True, max_length=50)),
                ('epcstart', models.CharField(blank=True, max_length=50)),
                ('epcend', models.CharField(blank=True, max_length=50)),
                ('performstart', models.CharField(blank=True, max_length=50)),
                ('performend', models.CharField(blank=True, max_length=50)),
                ('advancestart', models.CharField(blank=True, max_length=50)),
                ('advanceend', models.CharField(blank=True, max_length=50)),
                ('insurestart', models.CharField(blank=True, max_length=50)),
                ('insureend', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=900)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
